batch_title: TOPMed_AFIB_batch14a
input: AFIB_batch14a_mplx.xlsx 
batch_date: 2017-12-20
file_formats:
  - CRAM
attempt: a
num_records: 100
file_sizes: 21-29G
funding_source: NHGRI CCDG_Afib_Supp
project_code: proj-dm0017
